//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GNT_server.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Route
    {
        public int RouteID { get; set; }
        [Required(ErrorMessage = "會員ID不能為空")]
        public Nullable<int> MemberID { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public Nullable<int> Dest1 { get; set; }
        public Nullable<int> Dest2 { get; set; }
        public Nullable<int> Dest3 { get; set; }
        public Nullable<int> Dest4 { get; set; }
        public Nullable<int> Dest5 { get; set; }
        public Nullable<int> Dest6 { get; set; }
        public Nullable<int> Dest7 { get; set; }
        public Nullable<int> Dest8 { get; set; }

        [JsonIgnore]
        public virtual MemberInfo MemberInfo { get; set; }
        //[JsonIgnore]
        public virtual ShopInfo ShopInfo { get; set; }
        //[JsonIgnore]
        public virtual ShopInfo ShopInfo1 { get; set; }
        //[JsonIgnore]
        public virtual ShopInfo ShopInfo2 { get; set; }
        //[JsonIgnore]
        public virtual ShopInfo ShopInfo3 { get; set; }
        //[JsonIgnore]
        public virtual ShopInfo ShopInfo4 { get; set; }
        //[JsonIgnore]
        public virtual ShopInfo ShopInfo5 { get; set; }
        //[JsonIgnore]
        public virtual ShopInfo ShopInfo6 { get; set; }
        //[JsonIgnore]
        public virtual ShopInfo ShopInfo7 { get; set; }
    }
}
