//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GNT_server.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Route
    {
        public int RouteID { get; set; }
        public Nullable<int> MemberID { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public string Dest1 { get; set; }
        public string Dest2 { get; set; }
        public string Dest3 { get; set; }
        public string Dest4 { get; set; }
        public string Dest5 { get; set; }
        public string Dest6 { get; set; }
        public string Dest7 { get; set; }
        public string Dest8 { get; set; }
        public Nullable<bool> Enable { get; set; }
    
        public virtual MemberInfo MemberInfo { get; set; }
    }
}
