//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GNT_server.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class WebsiteReview
    {
        public int ReviewID { get; set; }
        [Required]
        public Nullable<int> MemberID { get; set; }
        public Nullable<System.DateTime> ReviewDate { get; set; }
        [Required]
        public string Type { get; set; }
        [Required]
        public string RContent { get; set; }
        public string Status { get; set; }
        public string Remark { get; set; }

        [JsonIgnore]
        public virtual MemberInfo MemberInfo { get; set; }
    }
}
